#!/usr/bin/env bash
# Regenerates packages/abi/src from the compiled contracts, as `as const` ABIs for viem.
set -euo pipefail

cd "$(dirname "$0")/.."
OUT="../packages/abi/src"
mkdir -p "$OUT"
forge build --silent

contracts=(PayeeRegistry PayeeResolver AgentVault PayRouter MockJPYC MandateGate)
index="$OUT/index.ts"
echo "// Generated by contracts/script/export-abi.sh. Do not edit." > "$index"

for name in "${contracts[@]}"; do
  const="$(echo "${name:0:1}" | tr '[:upper:]' '[:lower:]')${name:1}Abi"
  {
    echo "// Generated by contracts/script/export-abi.sh. Do not edit."
    printf 'export const %s = %s as const;\n' "$const" "$(jq '.abi' "out/${name}.sol/${name}.json")"
  } > "$OUT/${name}.ts"
  echo "export { ${const} } from \"./${name}.js\";" >> "$index"
done

echo "Exported ${#contracts[@]} ABIs to packages/abi/src"
